/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.javanese.kasir;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class login extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(login.class.getName());
    // Variabel static untuk menyimpan sesi login
    public static int idLoggedIn;
    public static String namaLoggedIn;
    public static String roleLoggedIn;
    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        logintxt = new javax.swing.JLabel();
        logicon = new javax.swing.JLabel();
        usertxt = new javax.swing.JLabel();
        userfield = new javax.swing.JTextField();
        passfield = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        loginbtn = new javax.swing.JButton();
        mainpanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 51, 255));
        jPanel2.setForeground(new java.awt.Color(51, 51, 255));

        logintxt.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        logintxt.setForeground(new java.awt.Color(255, 255, 255));
        logintxt.setText("LOGIN");

        logicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/javanese/kasir/images/icons8-user-80.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addComponent(logintxt)
                .addContainerGap(191, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logicon)
                .addGap(204, 204, 204))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(logicon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logintxt)
                .addGap(9, 9, 9))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 160));

        usertxt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        usertxt.setText("Username");
        jPanel1.add(usertxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, -1, -1));

        userfield.setToolTipText("");
        jPanel1.add(userfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 220, 40));
        jPanel1.add(passfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 220, 40));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Password");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, -1, -1));

        loginbtn.setBackground(new java.awt.Color(51, 51, 255));
        loginbtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        loginbtn.setForeground(new java.awt.Color(255, 255, 255));
        loginbtn.setText("LOGIN");
        loginbtn.addActionListener(this::loginbtnActionPerformed);
        jPanel1.add(loginbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 370, 110, 40));

        mainpanel.setBackground(new java.awt.Color(255, 255, 255));
        mainpanel.setLayout(new javax.swing.OverlayLayout(mainpanel));
        jPanel1.add(mainpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 490, 330));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbtnActionPerformed
        // TODO add your handling code here:
        String username = userfield.getText();
        String password = new String(passfield.getPassword());
        if(username.isEmpty() || password.isEmpty()){
            JOptionPane.showMessageDialog(this, "Username atau Password tidak terdeteksi");
            return;
        }
        try {
            Connection conn = koneksi.getConnection();
            // Query UNION yang mengambil ID asli dan Username dari masing-masing tabel
            String sql = "SELECT id_admin AS id_asli, username AS nama_asli, 'admin' AS role_palsu FROM admin WHERE username=? AND password=? " +
                         "UNION " +
                         "SELECT id_user AS id_asli, username AS nama_asli, 'user' AS role_palsu FROM user WHERE username=? AND password=?";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, username);
            pst.setString(2, password);
            pst.setString(3, username);
            pst.setString(4, password);
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                // SIMPAN KE SESSION: Ambil data asli dari database
                idLoggedIn = rs.getInt("id_asli");
                namaLoggedIn = rs.getString("nama_asli");
                roleLoggedIn = rs.getString("role_palsu");
                if (roleLoggedIn.equals("admin")) {
                    JOptionPane.showMessageDialog(this, "Selamat Datang Admin, " + namaLoggedIn);
                    new tampiladmin().setVisible(true); 
                    this.dispose();
                } else if (roleLoggedIn.equals("user")) {
                    JOptionPane.showMessageDialog(this, "Selamat Datang, " + namaLoggedIn);
                    new tampilbeli(0.03).setVisible(true); 
                    this.dispose();
                }
            } else {
                JOptionPane.showMessageDialog(this, "Username atau Password salah");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error Login: " + e.getMessage());
        }
    }//GEN-LAST:event_loginbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel logicon;
    private javax.swing.JButton loginbtn;
    private javax.swing.JLabel logintxt;
    private javax.swing.JPanel mainpanel;
    private javax.swing.JPasswordField passfield;
    private javax.swing.JTextField userfield;
    private javax.swing.JLabel usertxt;
    // End of variables declaration//GEN-END:variables
}
