/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.javanese.kasir;

/**
 *
 * @author Lenovo
 */
public class tampiladmin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(tampiladmin.class.getName());

    /**
     * Creates new form tampiladmin
     */
    public tampiladmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        sidebar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        homebtn = new javax.swing.JButton();
        belibtn = new javax.swing.JButton();
        dashboardtitle = new javax.swing.JLabel();
        cardstat = new javax.swing.JPanel();
        targetcard = new javax.swing.JPanel();
        targetlabel = new javax.swing.JLabel();
        targetnum = new javax.swing.JLabel();
        totalcard = new javax.swing.JPanel();
        totallabel = new javax.swing.JLabel();
        totalnum = new javax.swing.JLabel();
        unitcard = new javax.swing.JPanel();
        unitlabel = new javax.swing.JLabel();
        unitnum = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelstok = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        sidebar.setBackground(new java.awt.Color(51, 51, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("TOKO JAVA");

        homebtn.setBackground(new java.awt.Color(51, 51, 255));
        homebtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        homebtn.setForeground(new java.awt.Color(255, 255, 255));
        homebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/javanese/kasir/images/icons8-home-25.png"))); // NOI18N
        homebtn.setText("Home");
        homebtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        belibtn.setBackground(new java.awt.Color(51, 51, 255));
        belibtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        belibtn.setForeground(new java.awt.Color(255, 255, 255));
        belibtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/javanese/kasir/images/icons8-cart-30.png"))); // NOI18N
        belibtn.setText("Beli");
        belibtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        javax.swing.GroupLayout sidebarLayout = new javax.swing.GroupLayout(sidebar);
        sidebar.setLayout(sidebarLayout);
        sidebarLayout.setHorizontalGroup(
            sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(homebtn)
                    .addComponent(jLabel1)
                    .addComponent(belibtn))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        sidebarLayout.setVerticalGroup(
            sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(41, 41, 41)
                .addComponent(homebtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(belibtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        dashboardtitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        dashboardtitle.setText("DASHBOARD");

        cardstat.setBackground(new java.awt.Color(255, 255, 255));
        cardstat.setLayout(new java.awt.GridLayout(0, 3, 10, 10));

        targetcard.setBackground(new java.awt.Color(51, 51, 255));

        targetlabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        targetlabel.setForeground(new java.awt.Color(255, 255, 255));
        targetlabel.setText("DANA BULANAN");
        targetlabel.setToolTipText("");

        targetnum.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        targetnum.setForeground(new java.awt.Color(255, 255, 255));
        targetnum.setText("0");

        javax.swing.GroupLayout targetcardLayout = new javax.swing.GroupLayout(targetcard);
        targetcard.setLayout(targetcardLayout);
        targetcardLayout.setHorizontalGroup(
            targetcardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(targetcardLayout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(targetlabel)
                .addGap(32, 32, 32))
            .addGroup(targetcardLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(targetnum)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        targetcardLayout.setVerticalGroup(
            targetcardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(targetcardLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(targetlabel)
                .addGap(18, 18, 18)
                .addComponent(targetnum)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        cardstat.add(targetcard);

        totalcard.setBackground(new java.awt.Color(51, 51, 255));

        totallabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        totallabel.setForeground(new java.awt.Color(255, 255, 255));
        totallabel.setText("TOTAL STOK");
        totallabel.setToolTipText("");

        totalnum.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        totalnum.setForeground(new java.awt.Color(255, 255, 255));
        totalnum.setText("0");

        javax.swing.GroupLayout totalcardLayout = new javax.swing.GroupLayout(totalcard);
        totalcard.setLayout(totalcardLayout);
        totalcardLayout.setHorizontalGroup(
            totalcardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, totalcardLayout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addComponent(totallabel)
                .addGap(52, 52, 52))
            .addGroup(totalcardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(totalcardLayout.createSequentialGroup()
                    .addGap(80, 80, 80)
                    .addComponent(totalnum)
                    .addContainerGap(78, Short.MAX_VALUE)))
        );
        totalcardLayout.setVerticalGroup(
            totalcardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(totalcardLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(totallabel)
                .addContainerGap(136, Short.MAX_VALUE))
            .addGroup(totalcardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(totalcardLayout.createSequentialGroup()
                    .addGap(59, 59, 59)
                    .addComponent(totalnum)
                    .addContainerGap(59, Short.MAX_VALUE)))
        );

        cardstat.add(totalcard);

        unitcard.setBackground(new java.awt.Color(51, 51, 255));
        unitcard.setForeground(new java.awt.Color(255, 255, 255));

        unitlabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        unitlabel.setForeground(new java.awt.Color(255, 255, 255));
        unitlabel.setText("UNIT TERJUAL");

        unitnum.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        unitnum.setForeground(new java.awt.Color(255, 255, 255));
        unitnum.setText("0");

        javax.swing.GroupLayout unitcardLayout = new javax.swing.GroupLayout(unitcard);
        unitcard.setLayout(unitcardLayout);
        unitcardLayout.setHorizontalGroup(
            unitcardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, unitcardLayout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addComponent(unitlabel)
                .addGap(47, 47, 47))
            .addGroup(unitcardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(unitcardLayout.createSequentialGroup()
                    .addGap(80, 80, 80)
                    .addComponent(unitnum)
                    .addContainerGap(78, Short.MAX_VALUE)))
        );
        unitcardLayout.setVerticalGroup(
            unitcardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(unitcardLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(unitlabel)
                .addContainerGap(136, Short.MAX_VALUE))
            .addGroup(unitcardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(unitcardLayout.createSequentialGroup()
                    .addGap(59, 59, 59)
                    .addComponent(unitnum)
                    .addContainerGap(59, Short.MAX_VALUE)))
        );

        cardstat.add(unitcard);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        panelstok.setLayout(new java.awt.GridLayout(0, 3, 10, 10));

        jPanel5.setBackground(new java.awt.Color(102, 255, 255));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 185, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 239, Short.MAX_VALUE)
        );

        panelstok.add(jPanel5);

        jPanel4.setBackground(new java.awt.Color(51, 0, 51));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 185, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 239, Short.MAX_VALUE)
        );

        panelstok.add(jPanel4);

        jPanel9.setBackground(new java.awt.Color(204, 204, 0));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 185, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 239, Short.MAX_VALUE)
        );

        panelstok.add(jPanel9);

        jPanel8.setBackground(new java.awt.Color(255, 153, 51));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 185, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 239, Short.MAX_VALUE)
        );

        panelstok.add(jPanel8);

        jPanel6.setBackground(new java.awt.Color(102, 255, 255));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 185, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 239, Short.MAX_VALUE)
        );

        panelstok.add(jPanel6);

        jPanel7.setBackground(new java.awt.Color(102, 255, 255));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 185, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 239, Short.MAX_VALUE)
        );

        panelstok.add(jPanel7);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 185, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 239, Short.MAX_VALUE)
        );

        panelstok.add(jPanel3);

        jScrollPane1.setViewportView(panelstok);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(sidebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(dashboardtitle)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cardstat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sidebar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dashboardtitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cardstat, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new tampiladmin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton belibtn;
    private javax.swing.JPanel cardstat;
    private javax.swing.JLabel dashboardtitle;
    private javax.swing.JButton homebtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel panelstok;
    private javax.swing.JPanel sidebar;
    private javax.swing.JPanel targetcard;
    private javax.swing.JLabel targetlabel;
    private javax.swing.JLabel targetnum;
    private javax.swing.JPanel totalcard;
    private javax.swing.JLabel totallabel;
    private javax.swing.JLabel totalnum;
    private javax.swing.JPanel unitcard;
    private javax.swing.JLabel unitlabel;
    private javax.swing.JLabel unitnum;
    // End of variables declaration//GEN-END:variables
}
