/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.javanese.kasir;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;


/**
 *
 * @author Lenovo
 */
public class tampilkasir extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(tampilkasir.class.getName());

    /**
     * Creates new form tampilkasir
     */
    public tampilkasir() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    private void tambahStokLama(){
        try {
        String nama = JOptionPane.showInputDialog(this, "Masukkan Nama Produk:");
        if (nama == null || nama.isEmpty()) return;

        String jumlahStr = JOptionPane.showInputDialog(this, "Jumlah Stok yang Ditambah:");
        if (jumlahStr == null || jumlahStr.isEmpty()) return;
        
        int tambahStok = Integer.parseInt(jumlahStr);

        Connection conn = koneksi.getConnection();
        // SQL untuk update stok berdasarkan nama
        String sql = "UPDATE produk SET stok = stok + ? WHERE nama_produk = ?";
        PreparedStatement ps = conn.prepareStatement(sql);
        ps.setInt(1, tambahStok);
        ps.setString(2, nama);

        int hasil = ps.executeUpdate();
        if (hasil > 0) {
            JOptionPane.showMessageDialog(this, "Stok " + nama + " berhasil diperbarui!");
        } else {
            JOptionPane.showMessageDialog(this, "Produk tidak ditemukan!");
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        headertxt = new javax.swing.JLabel();
        subtxt = new javax.swing.JLabel();
        sellpanel = new javax.swing.JPanel();
        Sellicon = new javax.swing.JLabel();
        jualtxt = new javax.swing.JLabel();
        loginadmin = new javax.swing.JPanel();
        Beliicon1 = new javax.swing.JLabel();
        belitxt1 = new javax.swing.JLabel();
        buypanel = new javax.swing.JPanel();
        Beliicon2 = new javax.swing.JLabel();
        belitxt2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header.setBackground(new java.awt.Color(0, 102, 255));

        headertxt.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        headertxt.setForeground(new java.awt.Color(255, 255, 255));
        headertxt.setText("TOKO JAVA");

        subtxt.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        subtxt.setForeground(new java.awt.Color(255, 255, 255));
        subtxt.setText("Tempat Jual Beli Kepercayaan Anda");

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap(277, Short.MAX_VALUE)
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                        .addComponent(headertxt)
                        .addGap(248, 248, 248))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                        .addComponent(subtxt)
                        .addGap(277, 277, 277))))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addComponent(headertxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(subtxt)
                .addGap(34, 34, 34))
        );

        jPanel1.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 180));

        sellpanel.setBackground(new java.awt.Color(0, 102, 255));
        sellpanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sellpanelMouseClicked(evt);
            }
        });

        Sellicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/javanese/kasir/images/icons8-sell-50.png"))); // NOI18N

        jualtxt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jualtxt.setForeground(new java.awt.Color(255, 255, 255));
        jualtxt.setText("JUAL");

        javax.swing.GroupLayout sellpanelLayout = new javax.swing.GroupLayout(sellpanel);
        sellpanel.setLayout(sellpanelLayout);
        sellpanelLayout.setHorizontalGroup(
            sellpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sellpanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(sellpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Sellicon)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sellpanelLayout.createSequentialGroup()
                        .addComponent(jualtxt)
                        .addGap(9, 9, 9)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        sellpanelLayout.setVerticalGroup(
            sellpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sellpanelLayout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(Sellicon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jualtxt)
                .addGap(12, 12, 12))
        );

        jualtxt.getAccessibleContext().setAccessibleName("SELL");

        jPanel1.add(sellpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, 120, 120));

        loginadmin.setBackground(new java.awt.Color(0, 102, 255));
        loginadmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginadminMouseClicked(evt);
            }
        });

        Beliicon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/javanese/kasir/images/icons8-admin-80.png"))); // NOI18N

        belitxt1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        belitxt1.setForeground(new java.awt.Color(255, 255, 255));
        belitxt1.setText("Admin Login");

        javax.swing.GroupLayout loginadminLayout = new javax.swing.GroupLayout(loginadmin);
        loginadmin.setLayout(loginadminLayout);
        loginadminLayout.setHorizontalGroup(
            loginadminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginadminLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(loginadminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(belitxt1)
                    .addComponent(Beliicon1))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        loginadminLayout.setVerticalGroup(
            loginadminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginadminLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(Beliicon1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(belitxt1)
                .addContainerGap())
        );

        jPanel1.add(loginadmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 370, 120, 120));

        buypanel.setBackground(new java.awt.Color(0, 102, 255));
        buypanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buypanelMouseClicked(evt);
            }
        });

        Beliicon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/javanese/kasir/images/icons8-buy-50.png"))); // NOI18N

        belitxt2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        belitxt2.setForeground(new java.awt.Color(255, 255, 255));
        belitxt2.setText("BELI");

        javax.swing.GroupLayout buypanelLayout = new javax.swing.GroupLayout(buypanel);
        buypanel.setLayout(buypanelLayout);
        buypanelLayout.setHorizontalGroup(
            buypanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buypanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(buypanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Beliicon2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buypanelLayout.createSequentialGroup()
                        .addComponent(belitxt2)
                        .addGap(9, 9, 9)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        buypanelLayout.setVerticalGroup(
            buypanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buypanelLayout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(Beliicon2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(belitxt2)
                .addGap(12, 12, 12))
        );

        jPanel1.add(buypanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, 120, 120));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 541, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginadminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginadminMouseClicked
        // TODO add your handling code here:
        //buat disini ya contohnya dh ada dibawah
        new login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_loginadminMouseClicked

    private void buypanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buypanelMouseClicked
        // TODO add your handling code here:
        int pilihan = javax.swing.JOptionPane.showConfirmDialog(
            this,
            "Login untuk mendapatkan diskon 3%?",
            "Konfirmasi",
            javax.swing.JOptionPane.YES_NO_OPTION
        );

        if (pilihan == javax.swing.JOptionPane.YES_OPTION) {
            // ke halaman login
            new login().setVisible(true);
            this.dispose();
        } else {
            // langsung beli tanpa login
            new tampilbeli(false).setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_buypanelMouseClicked

    private void sellpanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sellpanelMouseClicked
        // TODO add your handling code here:
        // cek login
        if (com.javanese.kasir.login.idLoggedIn == 0) { 
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Anda harus login terlebih dahulu untuk mengakses fitur ini!", 
                "Akses Ditolak", 
                javax.swing.JOptionPane.WARNING_MESSAGE);
            // bawa ke form login
            new com.javanese.kasir.login().setVisible(true);
            this.dispose(); // Tutup halaman saat ini jika perlu
            return; 
        }
        String[] opsi = {"Produk Baru", "Tambah Stok (Lama)", "Batal"};
        int pilih = javax.swing.JOptionPane.showOptionDialog(
            this, 
            "Halo " + com.javanese.kasir.login.namaLoggedIn + ",\nPilih jenis penjualan produk:", 
            "Manajemen Stok", 
            javax.swing.JOptionPane.DEFAULT_OPTION, 
            javax.swing.JOptionPane.QUESTION_MESSAGE, 
            null, opsi, opsi[0]
        );
        if (pilih == 0) { // Produk Baru
            new FormProdukBaru().setVisible(true);
        } else if (pilih == 1) { // Tambah Stok
            tambahStokLama();
        }
    }//GEN-LAST:event_sellpanelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new tampilkasir().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Beliicon1;
    private javax.swing.JLabel Beliicon2;
    private javax.swing.JLabel Sellicon;
    private javax.swing.JLabel belitxt1;
    private javax.swing.JLabel belitxt2;
    private javax.swing.JPanel buypanel;
    private javax.swing.JPanel header;
    private javax.swing.JLabel headertxt;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jualtxt;
    private javax.swing.JPanel loginadmin;
    private javax.swing.JPanel sellpanel;
    private javax.swing.JLabel subtxt;
    // End of variables declaration//GEN-END:variables
}
