/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.javanese.kasir;
import java.awt.*;
//import java.sql.*;
import javax.swing.*;


/**
 *
 * @author Lenovo
 */
public class tampilbeli extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(tampilbeli.class.getName());
    private boolean userLogin = false;
    private double diskon = 0.0;
    /**
     * Creates new form tampilbeli
     */
    public tampilbeli() {
        initComponents();
        setupCustomLogic();
        this.setSize(1000, 600);
        //ngatur layout
        Container container = this.getContentPane();
        container.setLayout(new BorderLayout());
        container.add(jPanel2, BorderLayout.WEST);
        container.add(jTabbedPane1, BorderLayout.CENTER);
        this.setLocationRelativeTo(null);
        //panggil style
        styleSidebarButton(jButton1);
        styleSidebarButton(jButton2);
        styleSidebarButton(jButton3);
        styleSidebarButton(logoutbtn);
        }
// Constructor user login
    public tampilbeli(boolean userLogin) {
        this(); // panggil tampil beli
        this.userLogin = userLogin;
        if (userLogin) {
            this.diskon = 0.03; // 3%
        }
    }

    // Constructor kalo kirim diskon
    public tampilbeli(double diskon) {
        this(); 
        this.diskon = diskon;
        this.userLogin = diskon > 0;
    }

    // Fungsi ngatur layout
    private void setupCustomLogic() {
        // setup Container Keranjang
        cartcontainer.setLayout(new BoxLayout(cartcontainer, BoxLayout.Y_AXIS));
        cartscroll.setViewportView(cartcontainer);
        
        // sembunyiin header tab
        jTabbedPane1.setUI(new javax.swing.plaf.basic.BasicTabbedPaneUI() {
            @Override
            protected int calculateTabAreaHeight(int tabPlacement, int runCount, int maxTabHeight) { return 0; }
            @Override
            protected void paintTabArea(Graphics g, int tabPlacement, int selectedIndex) { }
        });

        // Setup Container Produk
        panelproduk.setLayout(new BoxLayout(panelproduk, BoxLayout.Y_AXIS));
        firstpanel.setViewportView(panelproduk);
        
        loadProduk();
        setLocationRelativeTo(null);
    }
    public void addToCart(String nama, int harga) {
        CartItemPanel item = new CartItemPanel(nama, harga, () -> {
            for (java.awt.Component c : cartcontainer.getComponents()) {
                if (c instanceof CartItemPanel && nama.equals(c.getName())) {
                    cartcontainer.remove(c);
                    break;
                }
            }
            cartcontainer.revalidate();
            cartcontainer.repaint();
        });

        item.setName(nama); 
        cartcontainer.add(item);
        cartcontainer.add(javax.swing.Box.createVerticalStrut(10));

        cartcontainer.revalidate();
        cartcontainer.repaint();

 
        jTabbedPane1.setSelectedIndex(1); 
    }

    private void loadProduk() {
        panelproduk.removeAll();
        try {
            java.sql.Connection conn = com.javanese.kasir.koneksi.getConnection(); 
            java.sql.Statement st = conn.createStatement();

            java.sql.ResultSet rs = st.executeQuery("SELECT nama_produk, harga FROM produk");

            while (rs.next()) {
                String nama = rs.getString("nama_produk"); 
                int harga = rs.getInt("harga");           
                ProductCardPanel card = new ProductCardPanel(nama, harga, "", () -> {
                    addToCart(nama, harga);
                });

                panelproduk.add(card);
                panelproduk.add(javax.swing.Box.createVerticalStrut(15));
            }
        } catch (Exception e) {
            System.err.println("Error Load Produk: " + e.getMessage());
        }
        panelproduk.add(Box.createVerticalGlue());
        panelproduk.revalidate();
        panelproduk.repaint();
    }
    //override button style
    private void styleSidebarButton(JButton btn) {
        btn.setContentAreaFilled(false); // Menghilangkan background kotak abu-abu
        btn.setBorderPainted(false);     // Menghilangkan garis pinggir
        btn.setFocusPainted(false);      // Menghilangkan garis putus-putus saat diklik
        btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR)); // Kursor jadi jari
        btn.setHorizontalAlignment(SwingConstants.LEFT); // Teks rata kiri
        btn.setForeground(Color.WHITE);  // Warna teks putih
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        logoutbtn = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        firstpanel = new javax.swing.JScrollPane();
        panelproduk = new javax.swing.JPanel();
        secondpanel = new javax.swing.JPanel();
        cartscroll = new javax.swing.JScrollPane();
        cartcontainer = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(51, 51, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("TOKO JAVA");

        jButton1.setBackground(new java.awt.Color(51, 51, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/javanese/kasir/images/icons8-home-25.png"))); // NOI18N
        jButton1.setText("Home");
        jButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setBackground(new java.awt.Color(51, 51, 255));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/javanese/kasir/images/icons8-sell-25.png"))); // NOI18N
        jButton2.setText("Jual");
        jButton2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jButton3.setBackground(new java.awt.Color(51, 51, 255));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/javanese/kasir/images/icons8-cart-30.png"))); // NOI18N
        jButton3.setText("Cart");
        jButton3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton3.addActionListener(this::jButton3ActionPerformed);

        logoutbtn.setBackground(new java.awt.Color(51, 51, 255));
        logoutbtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        logoutbtn.setForeground(new java.awt.Color(255, 255, 255));
        logoutbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/javanese/kasir/images/icons8-logout-25.png"))); // NOI18N
        logoutbtn.setText("Logout");
        logoutbtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        logoutbtn.addActionListener(this::logoutbtnActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logoutbtn)
                    .addComponent(jButton1)
                    .addComponent(jLabel1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(41, 41, 41)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(logoutbtn)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        firstpanel.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        panelproduk.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        panelproduk.setLayout(new javax.swing.BoxLayout(panelproduk, javax.swing.BoxLayout.Y_AXIS));
        firstpanel.setViewportView(panelproduk);

        jTabbedPane1.addTab("tab1", firstpanel);

        cartscroll.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        cartcontainer.setLayout(new javax.swing.BoxLayout(cartcontainer, javax.swing.BoxLayout.Y_AXIS));
        cartscroll.setViewportView(cartcontainer);

        javax.swing.GroupLayout secondpanelLayout = new javax.swing.GroupLayout(secondpanel);
        secondpanel.setLayout(secondpanelLayout);
        secondpanelLayout.setHorizontalGroup(
            secondpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cartscroll, javax.swing.GroupLayout.DEFAULT_SIZE, 639, Short.MAX_VALUE)
        );
        secondpanelLayout.setVerticalGroup(
            secondpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(secondpanelLayout.createSequentialGroup()
                .addComponent(cartscroll, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab2", secondpanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(39, 39, 39))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new tampilkasir().setVisible(true); 
        this.dispose();  
    }//GEN-LAST:event_jButton1ActionPerformed

    private void logoutbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutbtnActionPerformed
        // TODO add your handling code here:
        //konfimr dulu
        int konfirmasi = javax.swing.JOptionPane.showConfirmDialog(
            this, 
            "Apakah Anda yakin ingin logout?", 
            "Konfirmasi Logout", 
            javax.swing.JOptionPane.YES_NO_OPTION
        );
        if (konfirmasi == javax.swing.JOptionPane.YES_OPTION) {
            //bersihin session
            com.javanese.kasir.login.idLoggedIn = 0; 
            com.javanese.kasir.login.namaLoggedIn = null;
            com.javanese.kasir.login.roleLoggedIn = null;

            new com.javanese.kasir.tampilkasir().setVisible(true);
            this.dispose(); 

            javax.swing.JOptionPane.showMessageDialog(null, "Anda telah berhasil logout.");
        }
    }//GEN-LAST:event_logoutbtnActionPerformed
    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {                                     
        new tampilkasir().setVisible(true); 
        this.dispose();                   
    }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new tampilbeli().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cartcontainer;
    private javax.swing.JScrollPane cartscroll;
    private javax.swing.JScrollPane firstpanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton logoutbtn;
    private javax.swing.JPanel panelproduk;
    private javax.swing.JPanel secondpanel;
    // End of variables declaration//GEN-END:variables
}
